Repository ticaretistatistik/ticaretistatistik.github.io, pull requests merged in 2024-10, with the labels that each got.

#25 chore: Add GNU General Public License Version 3
  LICENSE
Labels: documentation

#24 CI/CD | Build and Deploy Workflows
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: ci-cd

#20 Update README.md with Turkish translations and add contributors section
  README.md
Labels: documentation

#16 Chore(deps): Bump docusaurus scoped dependencies from 3.1.1 to 3.5.2
  package-lock.json
  package.json
Labels: dependencies

#27 New Blog | 2024-2025-data-analysis-lessons
  blog/2024-10-07-lesson-data-analysis-installations/assets/mac/mac-terminal-finder-spotlight.jpeg
  blog/2024-10-07-lesson-data-analysis-installations/assets/mac/mac-terminal-interface.jpeg
  blog/2024-10-07-lesson-data-analysis-installations/assets/vscode/vscode-new-profile.png
  blog/2024-10-07-lesson-data-analysis-installations/assets/vscode/vscode-profile-create.png
  blog/2024-10-07-lesson-data-analysis-installations/assets/vscode/vscode-profile-import-file.png
  blog/2024-10-07-lesson-data-analysis-installations/assets/vscode/vscode-profiles.png
  blog/2024-10-07-lesson-data-analysis-installations/assets/vscode/vscode-settings.png
  blog/2024-10-07-lesson-data-analysis-installations/assets/windows/windows-powershell.png
  blog/2024-10-07-lesson-data-analysis-installations/index.md
Labels: blog

#30 fix(blog): Update link to installation script for Windows
  blog/2024-10-07-lesson-data-analysis-installations/index.md
Labels: blog

#36 docs: Update R documentation and installation instructions
  docs/r/index.md
  docs/r/kurulum.md
Labels: documentation, docs: r

#37 Remove unnecessary pages and added 'mezunlarımız' page
  docs/hakkimizda/index.md
  docs/hakkimizda/kulup.md
  docs/hakkimizda/mezunlarimiz.md
  docusaurus.config.js
  sidebars.js
  src/css/custom.css
  src/pages/mezunlarimiz.js
  src/pages/mezunlarimiz.module.css
Labels: documentation, ui/ux
